### ISSUE TITLE
demo on using this mqtt wrapper ?

### ISSUE THREAD

**Issue by IHIDCHAOS** [semirm-dev/go-common#1]
i copyed the "connection.go","config.go" in my project,then write code in "main.go"like below:
`package main

import (
	"gw/src/mqtt"
	"log"
	"time"
)

func main() {
	mqttConfig := mqtt.NewConfig()
	mqttConfig.KeepAlive = time.Second * 15
	mqttConfig.CleanSession = true
	mqttConfig.AutoReconnect = true
	mqttConfig.MsgChanDept = 100
	mqttConfig.PubQoS = 0
	mqttConfig.SubQoS = 0
	_mqtt, err := mqtt.NewConnection(mqttConfig)
	if err != nil {
		panic(err)
	}
	if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message) {
		log.Print(m)
	}); token.Wait() && token.Error() != nil {
		log.Print("mqtt subscribe error: ", token.Error())
	}
	if token := _mqtt.Publish("my/topic", []byte("message")); token.Wait() && token.Error() != nil {
		log.Print("mqtt publish error: ", token.Error())
	}
	select {}
}`
but the ide shows that error "Unresolved type" at line "if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message)",can you help me please ?
see picture [here](https://imgchr.com/i/KK5ff0)

**Comment by semirm-dev** [comment]
Hi,

That is because you use your own mqtt import “gw/src/mqtt” instead of mqtt "github.com/eclipse/paho.mqtt.golang"
This line, if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message), mqtt.Message must be from github.com/eclipse/paho.mqtt.golang", not your own import!

Try to change that and let me know how it works

Sent from Mail for Windows 10

From: IHIDCHAOS
Sent: Sunday, October 20, 2019 11:06 AM
To: semirm-dev/go-common
Cc: Subscribed
Subject: [semirm-dev/go-common] demo on using this mqtt wrapper ? (#1)

i copyed the "connection.go","config.go" in my project,then write code in "main.go"like below:
`package main
import (
"gw/src/mqtt"
"log"
"time"
)
func main() {
mqttConfig := mqtt.NewConfig()
mqttConfig.KeepAlive = time.Second * 15
mqttConfig.CleanSession = true
mqttConfig.AutoReconnect = true
mqttConfig.MsgChanDept = 100
mqttConfig.PubQoS = 0
mqttConfig.SubQoS = 0
_mqtt, err := mqtt.NewConnection(mqttConfig)
if err != nil {
panic(err)
}
if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message) {
log.Print(m)
}); token.Wait() && token.Error() != nil {
log.Print("mqtt subscribe error: ", token.Error())
}
if token := _mqtt.Publish("my/topic", []byte("message")); token.Wait() && token.Error() != nil {
log.Print("mqtt publish error: ", token.Error())
}
select {}
}`
but the ide shows that error "Unresolved type" at line "if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message)",can you help me please ?
see picture here

**Comment by IHIDCHAOS** [comment]
Yes! i import paho-mqtt as pmqtt in my main,

> import (
>	pmqtt "github.com/eclipse/paho.mqtt.golang"
>
>	"gw/src/mqtt"
>	"log"
>	"time"
>)

and modify this line
> if token := _mqtt.Subscribe("my/topic", func(c mqtt.Client, m mqtt.Message)

to

> if token := _mqtt.Subscribe("my/topic", func(c pmqtt.Client, m pmqtt.Message)

then it works. Thanks for your help!
